---
# tasks file for debian-hyprland
- name: "Install required packages"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - zram-tools
    - curl
    - git
    - ansible

- name: "Configure settings in zramswap configuration file"
  ansible.builtin.lineinfile:
    path: /etc/default/zramswap
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - regexp: '^#ALGO='
      line: 'ALGO=lz4'
    - regexp: "^#PERCENT="
      line: 'PERCENT=25'

- name: "Reload the zramswap service"
  ansible.builtin.service:
    name: zramswap
    state: reloaded

- name: "Change the sources.list to use trixie instead of bookworm"
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: 'bookworm'
    replace: 'trixie'

- name: "Update repositories cache and full upgrade"
  ansible.builtin.apt:
    upgrade: "full"
    update_cache: true

- name: "Run a full upgrade"
  ansible.builtin.apt:

- name: "Remove dependencies that are no longer required and purge their configuration files"
  ansible.builtin.apt:
    autoremove: yes
    purge: true

- name: "Run the equivalent of apt-get clean as a separate step"
  ansible.builtin.apt:
    clean: yes
