---
# tasks file for debian-hyprland
- name: "Install required packages"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - zram-tools
    - curl
    - git
    - ansible

- name: "Remove comment from ALGO setting in zramswap configuration file"
  ansible.builtin.lineinfile:
    path: /etc/default/zramswap
    regexp: '^#ALGO='
    line: 'ALGO=lz4'
  #  regexp: '{{ item.regexp }}'
  #  replace: '{{ item.replace }}'
  #with_items:
  #  - regexp: '^#ALGO='
  #    replace: '\1'
  #  - regexp: "^#PERCENT="
  #    replace: '\1'

#- name: "Configure PERCENT setting in zramswap configuration file"
#  ansible.builtin.lineinfile:
#    path: /etc/default/zramswap
#    regexp: "^PERCENT="
#    line: "PERCENT=25"
