---
# tasks file for debian-hyprland
- name: "Install required packages"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - zram-tools
    - curl
    - git
    - ansible

- name: "Configure settings in zramswap configuration file"
  ansible.builtin.lineinfile:
    path: /etc/default/zramswap
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - regexp: '^#ALGO='
      line: 'ALGO=lz4'
    - regexp: "^#PERCENT="
      line: 'PERCENT=25'

- name: "Change the sources.list to use trixie instead of bookworm"
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: 'bookworm'
    replace: 'trixie'
